const projectRoot = __dirname;

module.exports = {
  apps: [
    {
      name: 'misterf-web',
      cwd: projectRoot,
      script: 'dist/server.js',
      exec_mode: 'fork',
      instances: 1,
      watch: false,
      autorestart: true,
      max_memory_restart: '300M',
      time: true,
      env: {
        NODE_ENV: 'development',
        PORT: '3000',
        GEMINI_API_KEY: 'AIzaSyDpxu5hgbpVnJCSyFMTrxE8FSMOmfIoK38',
        GEMINI_MODEL: 'gemini-2.5-flash',
        APP_BASE_URL: 'http://localhost:3000',
        APP_SESSION_SECRET: '57622d3faf0f71e4cdaadd29fc1f1b63f7b53ad48a454b4c4bf0a0215f9f15db',
        SMTP_HOST: 'smtp.gmail.com',
        SMTP_PORT: '587',
        SMTP_SECURE: 'false',
        SMTP_USER: 'boniatillo@gmail.com',
        SMTP_PASSWORD: 'bnfk tdtf umwf vfnb',
        MAIL_FROM: 'Mister F <boniatillo@gmail.com>',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: '3000',
        GEMINI_API_KEY: 'AIzaSyDpxu5hgbpVnJCSyFMTrxE8FSMOmfIoK38',
        GEMINI_MODEL: 'gemini-2.5-flash',
        APP_BASE_URL: 'http://localhost:3000',
        APP_SESSION_SECRET: '57622d3faf0f71e4cdaadd29fc1f1b63f7b53ad48a454b4c4bf0a0215f9f15db',
        SMTP_HOST: 'smtp.gmail.com',
        SMTP_PORT: '587',
        SMTP_SECURE: 'false',
        SMTP_USER: 'boniatillo@gmail.com',
        SMTP_PASSWORD: 'bnfk tdtf umwf vfnb',
        MAIL_FROM: 'Mister F <boniatillo@gmail.com>',
      },
    },
  ],
};
